#!/bin/bash

#=============================
# <none> images cleanup script
#=============================

cclean

ilist=`docker images --filter "dangling=true" -q`

if [ "$ilist" != "" ];then

docker rmi $ilist

else
  echo -e "\nThere is no mirror of <none>"
fi
