#!/bin/bash

#=================================
# exited containers Cleanup script
#=================================
rm_ctns=$(docker ps -a -q -f 'status=exited' -f 'status=created' -f 'status=dead')
if [ -z "$rm_ctns" ];then
	echo -e "\nno exited containers need to delete"
else
	docker rm $rm_ctns
fi
